name: Java CI
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Clone Libgdx wiki
      run: |
        git clone https://github.com/libgdx/libgdx.wiki.git wiki_src
        rm -rf wiki_src/.git
    - name: Launch translator
      run: |
        java test.java
    - name: Add changes to git
      run: git add -A
